version: '3.8'

services:
  # Telegram Bot
  bot:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - DATABASE_NAME=${DATABASE_NAME:-telegram_bot}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_PER_MIN=${RATE_LIMIT_PER_MIN:-20}
      - METRICS_ENABLED=${METRICS_ENABLED:-true}
      - METRICS_PORT=${METRICS_PORT:-9091}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"