global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'telegram-bot'
    environment: 'production'

# 告警规则文件
rule_files:
  - '/etc/prometheus/alert-rules.yml'

# Alertmanager 配置（可选）
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - 'alertmanager:9093'

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Telegram Bot 应用指标
  - job_name: 'telegram-bot'
    static_configs:
      - targets: ['bot:9091']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Node Exporter（系统指标，可选）
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # Docker 容器指标（可选）
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['cadvisor:8080']